CREATE DATABASE PROMISE_TOGETHER DEFAULT CHARACTER SET UTF8;
USE PROMISE_TOGETHER;

CREATE TABLE MEMBER_TB(
	MEMBER_ID int(5) NOT NULL AUTO_INCREMENT,
	GROUP_ID int(5) DEFAULT 0,
	PHONE_NO char(12) NOT NULL,
	PRIMARY KEY (MEMBER_ID)
);

CREATE TABLE PROMISE_ALWAYS_TB(
	PROMISE_ALWAYS_ID int(5) NOT NULL AUTO_INCREMENT,
	GROUP_ID int(5) NOT NULL,
	TITLE char(30) NOT NULL,
	INPUT_TIME datetime NOT NULL,
	PRIMARY KEY (PROMISE_ALWAYS_ID)
);

CREATE TABLE PROMISE_ONCE_TB(
	PROMISE_ONCE_ID int(5) NOT NULL AUTO_INCREMENT,
	GROUP_ID int(5) NOT NULL,
	TITLE char(30) NOT NULL,
	CONTENT text NOT NULL,	
	REQUIRED_TIME tinyint(2) NOT NULL,
	END_TIME datetime NOT NULL,
	PRIMARY KEY (PROMISE_ONCE_ID)
);